// general

export const EXTENSION_VERSION = process.env.EXTENSION_VERSION;
export const GENERAL_PERMISSION_KEYS = [
  'USER_SHARE_COUNTRY',
  'USER_SHARE_LANGUAGE',
  'USER_SHARE_GENDER',
  'USER_SHARE_AGE',
  'USER_SHARE_DIAGNOSTICS',
  'USER_SHARE_INSTALLATION_ID',
  'USER_SHARE_IP',
  'SHOW_DEBUG_DATA'
];

export const FACEBOOK_PERMISSION_KEYS = [
  'FB_SHARE_SPONSORED_POSTS',
  'FB_SHARE_AD_TARGETING',
  'FB_SHARE_PUBLIC_PAGE_POSTS',
  'FB_SHARE_PUBLIC_USER_POSTS',
  'FB_SHOW_COLLECTION_STATUS'
];

export const YOUTUBE_PERMISSION_KEYS = [
  'YT_SHARE_AD_TARGETING',
  'YT_SHARE_ADS',
  'YT_SHARE_RECOMMENDED_VIDEOS',
  'YT_SHARE_WATCHED_VIDEOS'
];

export const ALL_PERMISSION_KEYS = [
  ...GENERAL_PERMISSION_KEYS,
  ...FACEBOOK_PERMISSION_KEYS,
  ...YOUTUBE_PERMISSION_KEYS
];
