import isElementInViewport from '../visible/isElementInViewport';
import notOverlapping from '../visible/notOverlapping';

import { HYPERFEED } from '../../constants';

const DIVS_WITH_IDS = 'div[id]';

const isHyperfeed = element => element.getAttribute('id').startsWith(HYPERFEED);

// Get the selector to use to select all the newsfeed posts.
// FB uses an autogenerated CSS class to style all the newsfeed posts. This
// functions returns the selector on that CSS class.
// TODO: this function also exists in tagPostElement.js. Should find a
// way to dedupe the code.
function getDivNewsfeedSelector() {
  var feedstart = document.querySelector('#ssrb_feed_start');
  var newsfeedClass = feedstart.nextElementSibling.querySelector('div').className;
  console.log('guo selector', `div [class="${newsfeedClass}"]`);
  return `div [class="${newsfeedClass}"]`;
}

const determineFbVersion = (/* istanbul ignore next */ doc = document) => {
  const pre2020 = Array.from(doc.querySelectorAll(DIVS_WITH_IDS)).filter(isHyperfeed);

  const DIV_HAS_ROLE_IS_ARTICLE = getDivNewsfeedSelector();

  const [version, elements] = pre2020.length
    ? ['pre2020', []] // if pre2020, return no elements at all, we don't want to do ANYTHING.
    : ['post2020', Array.from(doc.querySelectorAll(DIV_HAS_ROLE_IS_ARTICLE))];

  return {
    elements: elements.filter(isElementInViewport).reduce(notOverlapping, []),
    version
  };
};

export default determineFbVersion;
